2020-07-26 22:35:19,133 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\megatutorial\cat\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "D:\PycharmProjects\megatutorial\cat\auth\email.py", line 12, in send_password_reset_email
    user=user, token=token),
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\PycharmProjects\megatutorial\cat\templates\email\reset_password.txt", line 4, in top-level template code
    <a href="{{ url_for('reset_password', token=token, _external=True) }}">
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-07-26 22:36:17,515 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PycharmProjects\megatutorial\cat\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "D:\PycharmProjects\megatutorial\cat\auth\email.py", line 12, in send_password_reset_email
    user=user, token=token),
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\PycharmProjects\megatutorial\cat\templates\email\reset_password.txt", line 4, in top-level template code
    <a href="{{ url_for('reset_password', token=token, _external=True) }}">
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\Damir Kondakov\PycharmProjects\megatutorial\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-07-29 11:17:32,108 INFO: Microblog startup [in D:\PycharmProjects\megatutorial\cat\__init__.py:76]
